#ifndef GAME_GAMESTATE_H
#define GAME_GAMESTATE_H

typedef enum GameState
{
    GAMESTATE_START_MENU,
    GAMESTATE_PAUSED,
    GAMESTATE_PLAYING,
    GAMESTATE_COUNT

} GameState;

#endif // !GAME_GAMESTATE_H
